FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-go-album


FROM gcr.io/distroless/base-debian11
WORKDIR /
COPY --from=builder /docker-go-album /docker-go-album
EXPOSE 8080
CMD ["/docker-go-album"]